image: hirokimatsumoto/alpine-openjdk-11

stages:
  - build
  - test

before_script:
  - java -version
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - apk update && apk upgrade && apk add --no-cache git

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew check -i

